name: multifaith_calendar
description: Multi-faith calendar app.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  drift: ^2.20.0
  drift_flutter: ^0.2.8
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0
  uuid: ^4.5.1
  intl: ^0.20.0
  collection: ^1.18.0
  geolocator: ^12.0.0
  kosher_dart: ^2.0.18
  hijri: ^3.0.0
  google_fonts: ^8.0.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.20.0
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true